from datetime import datetime
current_time=(datetime.now())
print(current_time)
format1=current_time.strftime("%Y-%m-%d %H:M:%S")
print(format1)
format2=current_time.strftime("%B,%d,%Y")
print(format2)
format3=current_time.strftime("%A,%B,%Y")
print(format3)
format4=current_time.strftime("%A,%B,d,%Y,%H:,%M:,%S,%p")
print(format4)
format5=current_time.strftime("%a-%b-%d,%I,%Z,%Y")
print(format5)
format6=current_time.strftime("%a-%b-%d,%H:%M:%S IST %Y")
print(format6)
format8=current_time.strftime("%d-%m-%Y")
print(format8)
format9=current_time.strftime("%H-%M-%s")
print(format9)
format10=current_time.strftime("%B")
print(format10)
format11=current_time.strftime("%Y")
print(format11)